// Writes what GameVolt needs to know about Chrome Circuit's trophies, from
// the list the game itself uses (src/achievements.js), so the two cannot
// drift apart:
//   achievement_defs.sql — the 31 rows for Supabase (and GameVolt's schema.sql)
//   trophy_catalog.js    — the entry for TROPHY_CATALOG in /profile/index.html
// Run from the repo root:  node tools/gamevolt/export.mjs
import { writeFileSync } from 'node:fs';
import { TROPHIES, GAME_ID } from '../../src/achievements.js';

const sql = (v) => `'${String(v).replace(/'/g, "''")}'`;
const rows = TROPHIES.map((t, i) => `  (${[`${GAME_ID}-${t.id}`, GAME_ID, t.name, t.desc, t.icon, t.tier].map(sql).join(', ')}, ${i + 1})`);
writeFileSync(new URL('./achievement_defs.sql', import.meta.url), `-- Chrome Circuit: game row and its 31 trophies (15 bronze, 10 silver, 5 gold, 1 platinum).
-- Generated by tools/gamevolt/export.mjs from src/achievements.js; do not edit by hand.
INSERT INTO games (id, title, thumbnail_url) VALUES
  (${sql(GAME_ID)}, 'Chrome Circuit', '/assets/thumbnails/${GAME_ID}.webp')
ON CONFLICT (id) DO NOTHING;

INSERT INTO achievement_defs (id, game_id, title, description, icon, tier, sort_order) VALUES
${rows.join(',\n')}
ON CONFLICT (id) DO NOTHING;
`);

const js = (v) => `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
writeFileSync(new URL('./trophy_catalog.js', import.meta.url), `// Chrome Circuit's entry for TROPHY_CATALOG in GameVolt's /profile/index.html.
// Generated by tools/gamevolt/export.mjs from src/achievements.js; do not edit by hand.
'${GAME_ID}': [
${TROPHIES.map((t) => `    { id:${js(`${GAME_ID}-${t.id}`)}, icon:${js(t.icon)}, name:${js(t.name)}, desc:${js(t.desc)}, tier:${js(t.tier)} },`).join('\n')}
],
`);
console.log(`wrote ${TROPHIES.length} trophies`);
